version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    networks:
      - internal
    volumes:
      - type: volume
        source: zksingle-ksingle_zookeeper-data
        target: /var/lib/zookeeper/data
      - type: volume
        source: zksingle-ksingle_zookeeper-log
        target: /var/lib/zookeeper/log
      - type: volume
        source: zksingle-ksingle_zookeeper-secrets
        target: /etc/zookeeper/secrets
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS: true
    networks:
      - internal
      - shared
      - test
    volumes:
      - type: volume
        source: zksingle-ksingle_broker-data
        target: /var/lib/kafka/data
      - type: volume
        source: zksingle-ksingle_broker-secrets
        target: /etc/kafka/secrets
networks:
  internal:
  shared:
    driver: bridge
  test:
      driver: bridge
      driver_opts:
        com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  zksingle-ksingle_broker-data:
  zksingle-ksingle_broker-secrets:
  zksingle-ksingle_zookeeper-data:
  zksingle-ksingle_zookeeper-log:
  zksingle-ksingle_zookeeper-secrets: